#spring.datasource.url=jdbc:postgresql://localhost:5432/booking-db
#spring.datasource.username=postgres
#spring.datasource.password=123456
#spring.data.redis.host=localhost
#spring.data.redis.port=6379
#spring.data.redis.password=

spring.data.redis.url=${REDIS_URL}

spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0

spring.datasource.username=postgres.eprkuembjzpjxfykivjw

spring.datasource.password=Tranbaoan99

spring.datasource.hikari.maximum-pool-size=5

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.servlet.context-path=/api/v1
server.port=${PORT:8080}
